package com.vvcode.monguito.ui;

import com.mongodb.DBObject;
import com.mongodb.util.JSON;
import com.vvcode.monguito.controllers.MonguitoController;

public class EditUI extends javax.swing.JDialog {

    private DBObject object;
    private MonguitoController monguitoController;

    /** Creates new form EditUI */
    public EditUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public EditUI(java.awt.Frame parent, boolean modal, DBObject object, MonguitoController monguitoController) {
        super(parent, modal);
        initComponents();
        this.object = object;
        this.monguitoController = monguitoController;
        textEdit.setText(object.toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textEdit = new javax.swing.JTextArea();
        btnField = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit field");

        textEdit.setColumns(20);
        textEdit.setLineWrap(true);
        textEdit.setRows(5);
        jScrollPane1.setViewportView(textEdit);

        btnField.setText("Save");
        btnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addComponent(btnField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnField)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-475)/2, (screenSize.height-506)/2, 475, 506);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFieldActionPerformed

        DBObject obj = (DBObject) JSON.parse(textEdit.getText());
        monguitoController.update(obj);
        this.setVisible(false);

    }//GEN-LAST:event_btnFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                EditUI dialog = new EditUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textEdit;
    // End of variables declaration//GEN-END:variables
}
