package com.vvcode.monguito.ui;

import com.vvcode.monguito.controllers.MonguitoController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

public class MonguitoUI extends javax.swing.JFrame {

    private MonguitoController monguitoController;
    private JDialog aboutBox;

    /** Creates new form MonguitoUI */
    public MonguitoUI() {
        initComponents();
        initMongoDbController();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        toolRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDataBases = new javax.swing.JList();
        lblDbSelected = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCollections = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        lblCollectionSelected = new javax.swing.JLabel();
        btnFind = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstResponse = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        lblCount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lstSkip = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        lstLimit = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        tbExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        tbConfigurate = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        tbAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MongoDB GUI Tool");

        jLabel1.setText("DB:");

        jToolBar1.setRollover(true);

        toolRefresh.setText("Refresh");
        toolRefresh.setEnabled(false);
        toolRefresh.setFocusable(false);
        toolRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolRefreshActionPerformed(evt);
            }
        });
        jToolBar1.add(toolRefresh);

        lstDataBases.setFont(new java.awt.Font("Dialog", 1, 10));
        lstDataBases.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstDataBases.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDataBasesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstDataBases);

        lblDbSelected.setFont(new java.awt.Font("Dialog", 0, 10));
        lblDbSelected.setForeground(new java.awt.Color(204, 0, 0));
        lblDbSelected.setText("DBSelected");

        lstCollections.setFont(new java.awt.Font("Dialog", 1, 10));
        lstCollections.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstCollections.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCollectionsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstCollections);

        jLabel2.setText("Coll.:");

        lblCollectionSelected.setFont(new java.awt.Font("Dialog", 0, 10));
        lblCollectionSelected.setForeground(new java.awt.Color(204, 0, 0));
        lblCollectionSelected.setText("CollectionSelected");

        btnFind.setText("Find");
        btnFind.setEnabled(false);
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        lstResponse.setFont(new java.awt.Font("Dialog", 0, 10));
        lstResponse.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstResponse);

        jLabel3.setText("Count:");

        lblCount.setForeground(new java.awt.Color(0, 153, 204));
        lblCount.setText("0");

        jLabel5.setText("Skip:");

        lstSkip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0" }));

        jLabel6.setText("Limit:");

        lstLimit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "20", "40", "50" }));

        jMenu1.setText("File");

        tbExit.setText("Exit");
        tbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbExitActionPerformed(evt);
            }
        });
        jMenu1.add(tbExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        tbConfigurate.setText("Configurate");
        tbConfigurate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbConfigurateActionPerformed(evt);
            }
        });
        jMenu2.add(tbConfigurate);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        tbAbout.setText("About");
        tbAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAboutActionPerformed(evt);
            }
        });
        jMenu3.add(tbAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lstSkip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lstLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDbSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCollectionSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(504, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblDbSelected)
                    .addComponent(jLabel2)
                    .addComponent(lblCollectionSelected))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                    .addComponent(btnFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblCount)
                    .addComponent(jLabel5)
                    .addComponent(lstSkip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(lstLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-899)/2, (screenSize.height-611)/2, 899, 611);
    }// </editor-fold>//GEN-END:initComponents

    private void tbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_tbExitActionPerformed

    private void lstDataBasesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDataBasesValueChanged

        if (evt.getValueIsAdjusting()) {
            String db = monguitoController.getDataBases().get(lstDataBases.getSelectedIndex());
            lblDbSelected.setText(db);
            monguitoController.refreshCollections(db);
            lstCollections.setListData(monguitoController.getCollections().toArray());
            btnFind.setEnabled(false);
            lblCollectionSelected.setText("");
        }

    }//GEN-LAST:event_lstDataBasesValueChanged

    private void lstCollectionsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCollectionsValueChanged

        if (evt.getValueIsAdjusting()) {
            String collection = monguitoController.getCollections().get(lstCollections.getSelectedIndex());
            lblCollectionSelected.setText(collection);
            btnFind.setEnabled(true);
        }

    }//GEN-LAST:event_lstCollectionsValueChanged

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed

        String collection = monguitoController.getCollections().get(lstCollections.getSelectedIndex());

        int limit = Integer.parseInt(lstLimit.getSelectedItem().toString());
        int skip = Integer.parseInt(lstSkip.getSelectedItem().toString());
        int count = monguitoController.find(collection, skip, limit);

        lblCount.setText(Integer.toString(count));
        lstResponse.setListData(monguitoController.getResponse().toArray());


        List<String> lstModel = new ArrayList<String>();
        lstModel.add("0");
        int tmp = limit;
        skip = 0;
        while (tmp < count) {
            skip++;
            lstModel.add(Integer.toString(skip));
            tmp += limit;
        }
        lstSkip.setModel(new javax.swing.DefaultComboBoxModel(lstModel.toArray()));

    }//GEN-LAST:event_btnFindActionPerformed

    private void tbAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAboutActionPerformed

        AboutDialogUI aboutDialogUI = new AboutDialogUI(this, true);
        aboutDialogUI.setVisible(true);

    }//GEN-LAST:event_tbAboutActionPerformed

    private void tbConfigurateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbConfigurateActionPerformed

        ConfigurationsUI configurationsUI = new ConfigurationsUI(this, true);
        configurationsUI.setVisible(true);
        toolRefresh.setEnabled(true);

    }//GEN-LAST:event_tbConfigurateActionPerformed

    private void toolRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolRefreshActionPerformed

        initMongoDbController();
        toolRefresh.setEnabled(false);

    }//GEN-LAST:event_toolRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MonguitoUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblCollectionSelected;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblDbSelected;
    private javax.swing.JList lstCollections;
    private javax.swing.JList lstDataBases;
    private javax.swing.JComboBox lstLimit;
    private javax.swing.JList lstResponse;
    private javax.swing.JComboBox lstSkip;
    private javax.swing.JMenuItem tbAbout;
    private javax.swing.JMenuItem tbConfigurate;
    private javax.swing.JMenuItem tbExit;
    private javax.swing.JButton toolRefresh;
    // End of variables declaration//GEN-END:variables

    private void initMongoDbController() {

        try {
            monguitoController = new MonguitoController();

            lblDbSelected.setText("");
            lstDataBases.setListData(monguitoController.getDataBases().toArray());

            lblCollectionSelected.setText("");
            lstCollections.setListData(monguitoController.getCollections().toArray());

            lstResponse.setListData(monguitoController.getResponse().toArray());

        } catch (Exception exception) {

            JOptionPane.showMessageDialog(this, exception.toString(),
                    "DB connection", JOptionPane.ERROR_MESSAGE);

            lblDbSelected.setText("");
            lstDataBases.setListData((new ArrayList<String>()).toArray());
            lblCollectionSelected.setText("");
            lstCollections.setListData((new ArrayList<String>()).toArray());
            lstResponse.setListData((new ArrayList<String>()).toArray());
            
        }
    }
}
